// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLbbtGbUxGttNkN70NsxPhppgBlyL6MWE',
    appId: '1:811854327889:web:f10d626095c4560c508870',
    messagingSenderId: '811854327889',
    projectId: 'helpdesk-1ff3d',
    authDomain: 'helpdesk-1ff3d.firebaseapp.com',
    storageBucket: 'helpdesk-1ff3d.appspot.com',
    measurementId: 'G-7XY0Y1K0YG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmswhEHNCTvaQLyP-ClLtIfK5OuSGLWuQ',
    appId: '1:811854327889:android:3eaca0062f3f0a91508870',
    messagingSenderId: '811854327889',
    projectId: 'helpdesk-1ff3d',
    storageBucket: 'helpdesk-1ff3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9UcBvDzrZgFumS3rRvBpXf14oNUNkt8s',
    appId: '1:811854327889:ios:f8bdb0bb9c0db0f8508870',
    messagingSenderId: '811854327889',
    projectId: 'helpdesk-1ff3d',
    storageBucket: 'helpdesk-1ff3d.appspot.com',
    iosClientId: '811854327889-f2pnlv2079cago46f5vbnrl45t6bmvi5.apps.googleusercontent.com',
    iosBundleId: 'com.example.appPesquisaFurb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9UcBvDzrZgFumS3rRvBpXf14oNUNkt8s',
    appId: '1:811854327889:ios:93c8ea804ff84941508870',
    messagingSenderId: '811854327889',
    projectId: 'helpdesk-1ff3d',
    storageBucket: 'helpdesk-1ff3d.appspot.com',
    iosClientId: '811854327889-mjjc6iaoup12v8ara8pf5i46o5b2hu5n.apps.googleusercontent.com',
    iosBundleId: 'com.example.appPesquisaFurb.RunnerTests',
  );
}
